steps:
- name: gcr.io/cloud-builders/npm
  args: ['install']
  dir: 'web'
- name: gcr.io/cloud-builders/npm
  args: ['run', 'build']
  dir: 'web'
- name: firebase
  args: ['deploy', '--token', '$_FIREBASE_TOKEN']
