service: nekolog

provider:
  name: aws
  runtime: nodejs6.10
  stage: prd
  region: ap-northeast-1

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /events
          method: get
          cors: true
      - http:
          path: /events
          method: put
          cors: true

resources:
  Resources:
    eventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: eventsTable
        AttributeDefinitions:
          - AttributeName: petId
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: N
        KeySchema:
        - AttributeName: petId
          KeyType: HASH
        - AttributeName: createdAt
          KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    dynamoDbIamRole:
      Type: AWS::IAM::Policy
      DependsOn: eventsTable
      Properties:
        PolicyName: lambda-dynamodb
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:Scan
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
              Resource: arn:aws:dynamodb:*:*:table/*
        Roles:
          - Ref: IamRoleLambdaExecution


