service: nekolog-app

provider:
  name: aws
  runtime: nodejs6.10
  stage: prd
  region: ap-northeast-1

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /events
          method: get
          cors: true
      - http:
          path: /events
          method: put
          cors: true

resources:
  Resources:
    eventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: eventsTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
        - AttributeName: id
          KeyType: hash
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1


