# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:

  build:
    docker:
    - image: circleci/node:10
    working_directory: ~/repo/web
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package-lock.json" }}
        - v1-dependencies-
    - run: npm install
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package-lock.json" }}
    - run: cd web && npm run build
    - persist_to_workspace:
        root: .
        paths:
        - web

  test:
    docker:
    - image: circleci/node:10
    working_directory: ~/repo/web
    steps:
    - attach_workspace:
        at: web
    - run: npm run lint

  deploy:
    docker:
    - image: circleci/node:10
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package-lock.json" }}
        - v1-dependencies-
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package-lock.json" }}
    - run: npx firebase deploy --token $FIREBASE_TOKEN

workflows:
  version: 2
  build_and_test:
    jobs:
    - build
    - test:
        requires:
        - build